//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades.Helpers {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class ConfigEmail : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigEmail defaultInstance = ((ConfigEmail)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigEmail())));
        
        public static ConfigEmail Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("solucionesinformaticas9708@gmail.com")]
        public string Email_errores {
            get {
                return ((string)(this["Email_errores"]));
            }
            set {
                this["Email_errores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("y f y s x e f i r w v o x o g c")]
        public string Password_email_errores {
            get {
                return ((string)(this["Password_email_errores"]));
            }
            set {
                this["Password_email_errores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jdiego970831@gmail.com")]
        public string Email_recepcion_errores {
            get {
                return ((string)(this["Email_recepcion_errores"]));
            }
            set {
                this["Email_recepcion_errores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string Server_smtp_errores {
            get {
                return ((string)(this["Server_smtp_errores"]));
            }
            set {
                this["Server_smtp_errores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public string Port_server_errores {
            get {
                return ((string)(this["Port_server_errores"]));
            }
            set {
                this["Port_server_errores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("solucionesinformaticas9708@gmail.com")]
        public string Email_reportes {
            get {
                return ((string)(this["Email_reportes"]));
            }
            set {
                this["Email_reportes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("y f y s x e f i r w v o x o g c")]
        public string Password_email_reportes {
            get {
                return ((string)(this["Password_email_reportes"]));
            }
            set {
                this["Password_email_reportes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jdiego9708@gmail.com")]
        public string Email_recepcion_reportes {
            get {
                return ((string)(this["Email_recepcion_reportes"]));
            }
            set {
                this["Email_recepcion_reportes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string Server_smtp_reportes {
            get {
                return ((string)(this["Server_smtp_reportes"]));
            }
            set {
                this["Server_smtp_reportes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public string Port_server_reportes {
            get {
                return ((string)(this["Port_server_reportes"]));
            }
            set {
                this["Port_server_reportes"] = value;
            }
        }
    }
}
